// <auto-generated />
using System;
using AgriState_MiniTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgriState_MiniTracker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005105711_UpdateModelConstraints")]
    partial class UpdateModelConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgriState_MiniTracker.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 101,
                            Description = "Nutrients and fertilizers",
                            LocationId = 1,
                            Name = "Fertilizers"
                        },
                        new
                        {
                            CategoryId = 102,
                            Description = "Farm and estate tools",
                            LocationId = 1,
                            Name = "Tools"
                        },
                        new
                        {
                            CategoryId = 103,
                            Description = "Crop seeds and seedlings",
                            LocationId = 2,
                            Name = "Seeds"
                        },
                        new
                        {
                            CategoryId = 104,
                            Description = "Eco pesticides and fungicides",
                            LocationId = 2,
                            Name = "Pesticides"
                        });
                });

            modelBuilder.Entity("AgriState_MiniTracker.Models.InventoryItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("MinStockLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 101,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4350),
                            LocationId = 1,
                            MinStockLevel = 10m,
                            Name = "Fertilizer",
                            Quantity = 45m,
                            Unit = "Bags",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4350)
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 101,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4356),
                            LocationId = 1,
                            MinStockLevel = 15m,
                            Name = "Organic Compost",
                            Quantity = 8m,
                            Unit = "Tons",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4356)
                        },
                        new
                        {
                            ItemId = 3,
                            CategoryId = 102,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4358),
                            LocationId = 1,
                            MinStockLevel = 5m,
                            Name = "Pruning Shears",
                            Quantity = 24m,
                            Unit = "Units",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4358)
                        },
                        new
                        {
                            ItemId = 4,
                            CategoryId = 102,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4359),
                            LocationId = 1,
                            MinStockLevel = 5m,
                            Name = "Tractor Oil",
                            Quantity = 3m,
                            Unit = "Pcs",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4360)
                        },
                        new
                        {
                            ItemId = 5,
                            CategoryId = 103,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4361),
                            LocationId = 2,
                            MinStockLevel = 20m,
                            Name = "Tomato Seeds",
                            Quantity = 120m,
                            Unit = "Packets",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4361)
                        },
                        new
                        {
                            ItemId = 6,
                            CategoryId = 103,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4363),
                            LocationId = 2,
                            MinStockLevel = 15m,
                            Name = "Nutrient Solution",
                            Quantity = 60m,
                            Unit = "Liters",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4363)
                        },
                        new
                        {
                            ItemId = 7,
                            CategoryId = 104,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4365),
                            LocationId = 2,
                            MinStockLevel = 10m,
                            Name = "Bio-Neem Eco Pesticide",
                            Quantity = 5m,
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4365)
                        },
                        new
                        {
                            ItemId = 8,
                            CategoryId = 104,
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4366),
                            LocationId = 2,
                            MinStockLevel = 8m,
                            Name = "Fungicide Spray Max",
                            Quantity = 18m,
                            Unit = "Bottles",
                            UpdatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4366)
                        });
                });

            modelBuilder.Entity("AgriState_MiniTracker.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Code = "LOC-RAT",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4230),
                            Description = "Main Barn Storage",
                            Name = "Rathnapura"
                        },
                        new
                        {
                            LocationId = 2,
                            Code = "LOC-KDY",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4234),
                            Description = "Highland Greenhouse",
                            Name = "Kandy"
                        },
                        new
                        {
                            LocationId = 3,
                            Code = "LOC-KEG",
                            CreatedAt = new DateTime(2026, 10, 5, 10, 57, 11, 144, DateTimeKind.Utc).AddTicks(4236),
                            Description = "Processing Facility",
                            Name = "Kegalle"
                        });
                });

            modelBuilder.Entity("AgriState_MiniTracker.Models.Category", b =>
                {
                    b.HasOne("AgriState_MiniTracker.Models.Location", "Location")
                        .WithMany("Categories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AgriState_MiniTracker.Models.InventoryItem", b =>
                {
                    b.HasOne("AgriState_MiniTracker.Models.Category", "Category")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriState_MiniTracker.Models.Location", "Location")
                        .WithMany("InventoryItems")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("AgriState_MiniTracker.Models.Category", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("AgriState_MiniTracker.Models.Location", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
